// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe5OWYfdrfeVC2uxaHk2VLEB-3XM6ZKo8',
    appId: '1:261464207804:web:82e6600a477db840a33bb9',
    messagingSenderId: '261464207804',
    projectId: 'project-3-rahaf',
    authDomain: 'project-3-rahaf.firebaseapp.com',
    storageBucket: 'project-3-rahaf.appspot.com',
    measurementId: 'G-HTD4G2GHCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGC28lb4WtcqzCstm1wFYowxsz61LzfSw',
    appId: '1:261464207804:android:9ba661ed25823e2ba33bb9',
    messagingSenderId: '261464207804',
    projectId: 'project-3-rahaf',
    storageBucket: 'project-3-rahaf.appspot.com',
  );
}
